// Generated by Supabase CLI (run: npm run types)
// Temporary placeholder - will be replaced when you connect to Supabase

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      clients: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          first_name: string
          last_name: string
          phone: string
          email: string | null
          address: string
          suburb: string
          postcode: string
          latitude: number | null
          longitude: number | null
          notes: string | null
          is_active: boolean
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          first_name: string
          last_name: string
          phone: string
          email?: string | null
          address: string
          suburb: string
          postcode: string
          latitude?: number | null
          longitude?: number | null
          notes?: string | null
          is_active?: boolean
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          first_name?: string
          last_name?: string
          phone?: string
          email?: string | null
          address?: string
          suburb?: string
          postcode?: string
          latitude?: number | null
          longitude?: number | null
          notes?: string | null
          is_active?: boolean
        }
      }
      pets: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          client_id: string
          name: string
          species: 'dog' | 'cat' | 'other'
          breed: string | null
          weight_kg: number | null
          age_years: number | null
          temperament: string | null
          medical_notes: string | null
          photo_url: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          client_id: string
          name: string
          species: 'dog' | 'cat' | 'other'
          breed?: string | null
          weight_kg?: number | null
          age_years?: number | null
          temperament?: string | null
          medical_notes?: string | null
          photo_url?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          client_id?: string
          name?: string
          species?: 'dog' | 'cat' | 'other'
          breed?: string | null
          weight_kg?: number | null
          age_years?: number | null
          temperament?: string | null
          medical_notes?: string | null
          photo_url?: string | null
        }
      }
      services: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          name: string
          description: string | null
          base_price: number
          duration_minutes: number
          color: string
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          name: string
          description?: string | null
          base_price: number
          duration_minutes: number
          color?: string
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          name?: string
          description?: string | null
          base_price?: number
          duration_minutes?: number
          color?: string
        }
      }
      appointments: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          client_id: string
          pet_id: string
          service_id: string
          start_time: string
          end_time: string
          status: 'scheduled' | 'completed' | 'cancelled' | 'no_show'
          price: number
          payment_status: 'unpaid' | 'paid'
          payment_method: 'cash' | 'card' | 'payid' | null
          notes: string | null
          google_calendar_event_id: string | null
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          client_id: string
          pet_id: string
          service_id: string
          start_time: string
          end_time: string
          status?: 'scheduled' | 'completed' | 'cancelled' | 'no_show'
          price: number
          payment_status?: 'unpaid' | 'paid'
          payment_method?: 'cash' | 'card' | 'payid' | null
          notes?: string | null
          google_calendar_event_id?: string | null
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          client_id?: string
          pet_id?: string
          service_id?: string
          start_time?: string
          end_time?: string
          status?: 'scheduled' | 'completed' | 'cancelled' | 'no_show'
          price?: number
          payment_status?: 'unpaid' | 'paid'
          payment_method?: 'cash' | 'card' | 'payid' | null
          notes?: string | null
          google_calendar_event_id?: string | null
        }
      }
      appointment_pets: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          appointment_id: string
          pet_id: string
          service_id: string
          price: number
        }
        Insert: {
          id?: string
          created_at?: string
          updated_at?: string
          appointment_id: string
          pet_id: string
          service_id: string
          price: number
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          appointment_id?: string
          pet_id?: string
          service_id?: string
          price?: number
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

